* Getting yourself organized with Orgmode

** Concept: Headlines - Outline mode

Every headline starts with one or more * 

Visibility of the headline hierarchy:
- Local visibility cycling with =<TAB>=
- Global visibility cycling with =S-<TAB>=

Increase or decrease level with =S-M RIGHT= or =S-M LEFT=

Move up/down within a level with =S-M UP= or =S-M DOWN=

Move a headline under another top level headline:
Cursor on the headline and then =C-c C-w=


** Concept: ToDo keywords
Default is TODO and DONE 

Cycling through them with =S RIGHT= or =S LEFT=

More keywords can be defined with a line =#+SEQ_TODO=:
- Items left of | are TODO items
- Items right of | are DONE items

Activate line with =C-c C-c=

Get a menu of all keywords: =C-c C-t=

** Concept: Schedule, deadline and agenda view
Scheduling is done with =C-c C-s=

Deadlines are defined with =C-c C-d=

Switch to agenda view with =C-a a=

Follow mode with =S-F=

Move forward with =f= or backward with =b=

** Concept: Repeating tasks

Some tasks occur frequently, so we should schedule them frequently. 

To schedule a repeating task you need to modify the timestamp: 
eg. < 2018-07-04 Mer [REPEAT]> 

The term [REPEAT] can be: 

- =+1w= Next occurence in one week. (w=week, d=day, m=month, y=year).
- =++1w= Next occurence on the same day of week, but definitely in the future.
- =.+4w= Next occurence 4 weeks after the task is marked as done.


** Concept: Checklists
Checklists provide a simple "checkoff" list.

Checklists start with 
- [ ] Text for checkitem

New checklist lines can be added with =C-c C-x M= (the capital letter 'M' not the Meta key)

You can see the completion of the checklist with =[/]= or =[%]= on the headline

Checkboxes are toggled with =C-c C-c=

** Concept: Tags 
Tags can be added to headlines and are often used as a way to mark GTD contexts.

Tags can be predefined with a line =#+TAGS: PHONE(o)......=
at the beginning of the file. 

To assign a tag to a headline use =C-c C-q=

If you have predefined tags with keys assigned, you see a menu, but you still can enter free tags by
pressing =<TAB>=. Finish definition with =Enter=.

** Concepts: Agenda mode (adavanced)

In the agenda view: 

| Key   | Function                                |
|-------+-----------------------------------------|
| =A=   | Agenda for the current week or day      |
| =S-l= | Timeline for current buffer             |
| =t=   | List of all TODO entries                |
| =S-t= | Entries with a special TODO keyword     |
| =m=   | Match tags / properties / TODO keywords |
| =S-m= | Like before, but only TODO entries      |
| =s=   | Search for keywords                     |


* Credits

Most of these notes comes from [[https://www.youtube.com/playlist?list=PLVtKhBrRV_ZkPnBtt_TD1Cs9PJlU0IIdE][Rainer König video serie on OrgMode tutorial]].
